export type Lang = "en" | "ar";

export const STRINGS: Record<Lang, Record<string, string>> = {
  en: {
    addRoot:      "Add Root",
    addChild:     "Add Branch",
    delete:       "Delete",
    duplicate:    "Duplicate",
    rename:       "Rename",
    color:        "Color",
    expand:       "Collapse / Expand",
    saveAs:       "Save as",
    open:         "Open",
    json:         "JSON file",
    png:          "PNG image",
    pdf:          "PDF",
    splashTitle:  "Welcome to Tree Builder",
    splashNew:    "Add new root",
    splashOpen:   "Open saved tree",
    showDetails:  "Show details",
    hideDetails:  "Hide details",
    details:      "Node details",
    editName:     "Edit name",
    pickColor:    "Pick node color",
    confirm:      "Confirm",
    cancel:       "Cancel",
    save:         "Save",
  },

  ar: {
    addRoot:      "اضف الجذر",
    addChild:     "اضف فرع",
    delete:       "حذف",
    duplicate:    "تكرار",
    rename:       "تعديل الاسم",
    color:        "تغيير اللون",
    expand:       "طي/توسيع",
    saveAs:       "حفظ كـ",
    open:         "فتح",
    json:         "ملف JSON",
    png:          "صورة PNG",
    pdf:          "PDF",
    splashTitle:  "السلام عليكم - تشجيرات",
    splashNew:    "اضف جذر جديد",
    splashOpen:   "فتح شجرة محفوظة",
    showDetails:  "إظهار التفاصيل",
    hideDetails:  "إخفاء التفاصيل",
    details:      "تفاصيل العقدة",
    editName:     "تعديل الاسم",
    pickColor:    "اختر لون العقدة",
    confirm:      "تأكيد",
    cancel:       "إلغاء",
    save:         "حفظ",
  },
};
